# Generated by Django 2.1.3 on 2018-11-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20181113_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, verbose_name='email address'),
        ),
    ]
